### ISSUE TITLE
Event API not accepting banner_url

### ISSUE THREAD

**Issue by nachovz** [breatheco-de/assets#2]
@alesanchezr 
_ banner_url _ is always saved as _null_

Try:

{
        "description": "4Geeks Nights - Learn to Code for Free Coding is no longer a dream. We are closing the gap and bringing coding to your life. A master platform, full of exercises and content, for free. To begin, we will give you free access to our Coding Introduction Program, where you will find everything you need to start your training as a software developer. HTML, CSS, Bootstrap, JavaScript and more. This is not only reading, videos, and tutorials, but tons of exercises and projects to work with.We have five -probably more- GREAT reasons why you should be in our 4Geeks Nights event on June 28th.- You will get FREE access to the Coding Intro Program and platform. Learn to Code has never been easy and better;- You will get free mentorship hours every week;- Our Career Support program speaks for itself. You will meet our Alumni; one of them will talk about his projects and experience at 4Geeks!- You will have fun while meeting our entire team & office: Founders, instructors, partners and classroom spaces. Have a drink with us!- You will get the details about our Software Program.",
    	"title" : "4Geeks Nights: INFO+CODING+GAMES+DRINKS",
        "url" : "https://www.eventbrite.com/e/4geeks-nights-infocodinggamesdrinks-tickets-46847266435",
	    "capacity" : 100,
	    "logo_url" : "https://pbs.twimg.com/profile_images/930433054371434496/v8GNrusZ_400x400.jpg",
        "invite_only": "0",
        "event_date": "2018-06-28 18:00:00",
        "type": "intro_to_coding",
        "city_slug": "mia",
        "address": "66 West Flagler Street #900, Miami, FL 33130",
        "banner_url": "http://placehold.it/800x400"
    }

**Comment by alesanchezr** [comment]
Creo que ya, prueba.
