### ISSUE TITLE
traductor con problema

### ISSUE THREAD

**Issue by GabrielValdiviaGaboloso** [breatheco-de/assets#211]
traductor de lenguaje con problema en la clase de día 3 de Basics of css

**Comment by ElviraQDP** [comment]
Me podrías decir en que lección o mandarme un pantallazo del error por favor? gracias

**Comment by GabrielValdiviaGaboloso** [comment]
***@***.***D731F2.28D6EE60]


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Elvira ***@***.***>
Enviado: jueves, 15 de abril de 2021 12:22
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [breatheco-de/assets] traductor con problema (#211)


Me podrías decir en que lección o mandarme un pantallazo del error por favor? gracias

**Comment by GabrielValdiviaGaboloso** [comment]
***@***.***D731F2.54CFF340]


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Elvira ***@***.***>
Enviado: jueves, 15 de abril de 2021 12:22
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [breatheco-de/assets] traductor con problema (#211)


Me podrías decir en que lección o mandarme un pantallazo del error por favor? gracias
