### ISSUE TITLE
problema de traduccion

### ISSUE THREAD

**Issue by GabrielValdiviaGaboloso** [breatheco-de/assets#212]
![image](https://user-images.githubusercontent.com/55467608/114906910-87211d80-9de8-11eb-8630-a9366365630b.png)
![image](https://user-images.githubusercontent.com/55467608/114907037-aa4bcd00-9de8-11eb-9a79-73a8c0ca7ace.png)

**Comment by ElviraQDP** [comment]
Estamos trabajando en ello!
