### ISSUE TITLE
IMPORTANT FOR MIRIADAX COURSE: Quiz doesn't work

### ISSUE THREAD

**Issue by victormgomezp** [breatheco-de/assets#234]
This quiz it doesn't work: https://assets.breatheco.de/apps/quiz/bootstrap-quiz

![image](https://user-images.githubusercontent.com/62053368/118510304-22cbe380-b731-11eb-8b6c-15dbe564323c.png)

**Comment by alesanchezr** [comment]
done! Thank you!

**Comment by victormgomezp** [comment]
@alesanchezr esto no está resuelto todavía, le acabo de dar clic al enlace y sigue mostrando el mismo mensaje.
