### ISSUE TITLE
day-01 Answer:Bootstrap

### ISSUE THREAD

**Issue by wotanCode** [breatheco-de/assets#237]
day-01 Answer:Bootstrap
error on the quiz. Cant open

"There was a problem loading the quiz:
Ther json file bootstrap-quiz was not found"
![day-01](https://user-images.githubusercontent.com/72775296/119437534-52a85780-bcec-11eb-96df-62afad4b95b6.jpg)

**Comment by alesanchezr** [comment]
Finally fixed :) thank you
