### ISSUE TITLE
Create a PDF certificate for students on-demand

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/assets#38]
This is an example of one of the certificates the academy gives to the students on completion of any course:
![screen shot 2018-12-18 at 12 48 33 pm](https://user-images.githubusercontent.com/426452/50173897-be3d9d80-02c6-11e9-8bcd-660c30c216ff.png)

First you would need to building the HTML based on 2 variables:
- **The cohort slug**: You will use it to get the cohort name, the course name, the graduation date and the total hours completed and the teacher signature.
- **The Student ID**: You will use it to get the student name.

Note: you can get all the information using the [BreatheCode's API](https://github.com/breatheco-de/api).

After the HTML looks amazing work on generating the PDF on the client-side using [this library jsPDF](https://github.com/MrRio/jsPDF) or [this library with react.js](https://medium.com/@shivekkhurana/how-to-create-pdfs-from-react-components-client-side-solution-7f506d9dfa6d) or any other library you may like.

In the end, the application should receive the Student ID and the Cohort Slug and that should be enough to generate and visualize a PDF with the student certificate, the URL can be something like this:
```
https://cert.breatheco.de/student/:student_id/cohort/:cohort_slug
```

### Important

If the student has not graduated or did not complete the program the certificate will not be generated, an 404 error will be shown on the screen. You can know if a student has graduated from the BreatheCode's API.

**Comment by Camilocoo** [comment]
i will work on this :) do you want the html to be responsive ?

**Comment by Camilocoo** [comment]
Do you know the name of the family font you are using on the preview ?

**Comment by alesanchezr** [comment]
No i don't

**Comment by alesanchezr** [comment]
No, the HTML does not have to be responsive, what matters in the end is the PDF
