### ISSUE TITLE
New APP: Email Message Renderer

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/assets#39]
This app will live under [https://assets.breatheco.de/apps/message](https://assets.breatheco.de/apps/message)

Using the [BreatheCode's Message API](https://assets.breatheco.de/apis/message/) we need an app that does the following:

- [ ] At first, it loads all the message types from the API and displays a dropdown to select what message type you want to see the email template from.
- [ ] after the user selects one of the message types, it displays the HTML email template of that message with some sample data.

Note: the interface should be similar to the Repl.it Maker or the Event Checking App.

**Comment by Camilocoo** [comment]
i will work on this

**Comment by alesanchezr** [comment]
Do not start this until I finish the wireframes for this.

**Comment by Camilocoo** [comment]
Ok
