### ISSUE TITLE
Unit Testing for Resources API

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/assets#73]
We need to implement unit tests for the resources api

https://github.com/breatheco-de/assets/tree/master/test

**Comment by alesanchezr** [comment]
Man, hay que desarrollar un script que haga un loop por todos los resources y verifique que no haya ningun URL con 404, puedes?

En esta carpeta hay varios ejemplos de tests:
https://github.com/breatheco-de/assets/tree/master/test

**Comment by Camilocoo** [comment]
@alesanchezr dale ya me pongo en eso
